www/rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index', views.index, name='index'),
    url(r'^about', views.about, name='about'),
    # url(r'^register', views.register, name='register'),
    # url(r'^login', views.user_login, name='login'),
    # url(r'^logout', views.user_logout, name='logout'),

    # User of ?P<name>
    # In django, named capturing groups are passed to your view as "KEYWORD ARGUMENTS."
    # Unnamed capturing groups (just a parenthesis) are passed to your view as "ARGUMENTS".
    # The ?P is a named capturing group, as opposed to an unnamed capturing group.
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    # url(r'^wb_search/$', views.webhose_search, name='webhose_search'), ## we won't do this in 1st step, merged with category
    url(r'^goto/$', views.track_url, name='goto'),
    url(r'^register_profile/$', views.register_profile, name='register_profile'),
    url(r'^profile/(?P<username>[\w\+]+)/$', views.profile, name='profile'),
    url(r'^list_profiles/$', views.list_profiles, name='list_profiles'),
]

www/www_site/urls.py
from django.conf.urls import url
from django.contrib import admin
from rango import views
from django.conf.urls import include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^accounts/register/$', views.MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

## registration.backends.simple.urls mappings
# registration -> /accounts/register/
# registration complete -> /accounts/register/complete/
# login -> /accounts/login/
# logout -> /accounts/logout/
# password change -> /password/change/
# password reset -> /password/reset/
# activation complete (used in the two-step registration) -> activate/complete/
# activate (used if the account action fails) -> activate/<activation_key>/

# ^accounts/ ^register/closed/$ [name='registration_disallowed']
# ^accounts/ ^register/complete/$ [name='registration_complete']
# ^accounts/ ^register/$ [name='registration_register']
# ^accounts/ ^login/$ [name='auth_login']
# ^accounts/ ^logout/$ [name='auth_logout']
# ^accounts/ ^password/change/$ [name='auth_password_change']
# ^accounts/ ^password/change/done/$ [name='auth_password_change_done']
# ^accounts/ ^password/reset/$ [name='auth_password_reset']
# ^accounts/ ^password/reset/complete/$ [name='auth_password_reset_complete']
# ^accounts/ ^password/reset/done/$ [name='auth_password_reset_done']
# ^accounts/ ^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$ [name='auth_password_reset_confirm']

www/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)

    # http://stackoverflow.com/questions/427102/what-is-a-slug-in-django
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Page(models.Model):
    category = models.ForeignKey(Category) # one to many relationship ! 1 category has many page
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.name

www/rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, label="Enter Category Name", help_text='Please enter the category name: ')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # Django models use the Meta class to contain extra information about the model
    # that would not necessarily be appropriate to contain within the model class itself.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name', ) # only include these fields

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, label="Enter Page Title", help_text='Please enter the Title of the page: ')
    url = forms.URLField(max_length=200, label="Enter Page URL", help_text='Please enter the URL of the page: ')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0) ## by default it is required field

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page
        exclude = ('category', ) # only exclude these fields. Alternate: "fields = ('title', 'url', 'views')"

    # override the default checking method
    def clean(self):
        print("Checking anything ??")
        cleaned_data = self.cleaned_data # Form have the cleaned_data key/value pair of each form entry
        url = cleaned_data.get('url')

        # url is not empty and also donot start with http://
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        exclude = ('user',)

www/rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm
from rango.forms import UserForm, UserProfileForm
from rango.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime
from registration.backends.simple.views import RegistrationView
from rango.api.webhose import run_query
from django.shortcuts import redirect
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.conf import settings

# Create your views here.

def index(request):
    # request.session.set_test_cookie()

    category_list = Category.objects.order_by('-likes')[:5]
    pages_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list}
    context_dict['pages'] = pages_list

    #### Below code works with checking COOKIE in client side ####
    # Obtain response object early so we can add cookie information
    # response = render(request, 'rango/index.html', context=context_dict)
    # call the helper function to handle the cookies
    #visitor_cookie_handler(request, response)
    ##############################################################

    ### Below code works with checking COOKIE in client side ####
    # No need to obtain response object early as we are getting the data from server side
    # call the helper function to handle the cookies
    visitor_cookie_handler_using_session(request)
    context_dict['visits'] = request.session['visits']

    response = render(request, 'rango/index.html', context=context_dict)
    #############################################################

    return response

def visitor_cookie_handler(request, response):
    # Get the number of visits to the site
    # We use the COOKIES.get() function to obtain the visits cookie
    visits = int(request.COOKIES.get('visits', '1'))

    last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now()))
    last_visit_time   = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).seconds > 2:
        visits += 1
        response.set_cookie('last_visit', str(datetime.now()))
    else:
        visits = 1
        response.set_cookie('last_visit', last_visit_cookie)

    response.set_cookie('visits', visits)


def get_server_side_cookie(request, cookie, default_val = None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler_using_session(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).seconds > 0:
        visits += 1
        request.session['last_visit'] = str(datetime.now())
    else:
        visits = 1
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits


def webhose_search(request):
    result_list = []
    query = ""
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)

    return render(request, 'rango/search.html', {'result_list': result_list, 'query': query})

def show_category(request, category_name_slug):
    context_dict = {}
    try :
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict = {'pages': pages, 'category': category}
        # print("context_dict: ", context_dict)
        # context_dict['pages'] = pages
        # context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None

    ### Merging Webhose search with Category
    context_dict['query'] = category.name
    result_list = []
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)
            context_dict['query'] = query
            context_dict['result_list'] = result_list

    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == 'GET':
        pass
        # print(request.method + " method automatically called")

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        # check for validation on the data
        if form.is_valid():
            form.save(commit=True)
            return index(request) # redirecting to the index page(index function)
        else:
            # as of now print the error in the terminal
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)  # load the category after/before submitting form
    except Category.DoesNotExist:
        category = None

    if request.method == 'POST':
        page_form = PageForm(request.POST)  # binding data from the POST request to the form
        # print("form: ", form)
        if page_form.is_valid(): # We call the form’s is_valid() method;
                            # if it’s not True, we go back to the template with the form.
            if category:
                page = page_form.save(commit=False)
                page.category = category
                page.views = 0
                page.save() # do the save now, once category is inserted
                return show_category(request, category_name_slug)
        else:
            print(form.errors)

    # if method is GET request
    # print("category_name_slug", category_name_slug)
    page_form = PageForm() ## If method is GET request, it will create the PageForm

    # perform when submitting the form or POST request

    context_dict = {'form': page_form, 'category': category} ## load the form
    return render(request, 'rango/add_page.html', context_dict)

# def register(request):
#     # A boolean value to tell whether the registration was successful.
#     registered = False # By default, registration is not successful
#
#     if request.method == 'POST':
#         user_form = UserForm(data=request.POST)
#         userprofile_form = UserProfileForm(data=request.POST)
#
#         if user_form.is_valid() and userprofile_form.is_valid():
#             # save the user's form data to the database.
#             # Direct save is possible as it already has password data from form
#             user = user_form.save()
#
#             # hash the provided password using set_password() method
#             user.set_password(user.password)
#
#             # update the user in the database with hashed password
#             user.save()
#
#             ## Now sortout the user_profile form
#             # We can't directly save the userprofile as we need to provide the user instance else it will
#             # violate the integrity
#             profile = userprofile_form.save(commit=False)
#             profile.user = user
#             if 'picture' in request.FILES:
#                 profile.picture = request.FILES['picture']
#
#             # Now we can save the userprofile
#             profile.save()
#
#             # Everything done ! Thus change the value of registered to True
#             registered = True
#         else:
#             # print the errors in the Console
#             print(user_form.errors, userprofile_form.errors)
#     else:
#         # Load both the forms for the request.GET method
#         user_form = UserForm()
#         userprofile_form = UserProfileForm()
#
#     context_dict = {'user_form': user_form, 'profile_form': userprofile_form, 'registered': registered}
#     # Render the template depending upon the context
#     return render(request, 'rango/register.html', context=context_dict)

# def user_login(request):
#     # If request.method == 'POST', try to pull out the relevant information
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#
#         user = authenticate(username=username, password=password) # django's own matchin mechanism
#         if user:
#             if user.is_active:
#                 login(request, user) ## django login method
#                 print("Login success !")
#                 return HttpResponseRedirect(reverse('index'))
#             else:
#                 return HttpResponse("Your Account is disabled.")
#         else:
#             print("Invalid login details: {0} {1}".format(username, password))
#             return HttpResponse("Invalid login details supplied.")
#     else:
#         # load the login form for the GET request
#         return render(request, 'rango/login.html')

# @login_required
# def user_logout(request):
#     logout(request)
#     return HttpResponseRedirect(reverse('index'))

def about(request):
    # if request.session.test_cookie_worked():
    #     print("TEST COOKiE WORKED !")
    #     request.session.delete_test_cookie()

    return render(request, 'rango/about.html')


class MyRegistrationView(RegistrationView):
    print("coming here or not !")
    def get_success_url(self, user=None):
        print("hitting get_succss_url")
        return reverse('rango:register_profile')


def track_url(request):
    page_id = None
    url = '/rango/'

    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']

            try:

www/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
<br/>
<div>
    <img src="{{ MEDIA_URL }}about.jpg"/>
</div>
<div>
    <br/>
    <p>I am Sayed Anisul Hoque. Enthusiast in Big data ! Apache Spark and love Python.</p>
</div>
{% endblock %}

www/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add Category
{% endblock %}

{% block body_block %}
<div class="jumbotron">
    <h2 class="display-4">Add a Category</h2>
</div>
<div>
    <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            {{ field.errors }}
            <!--{{ field.help_text }}-->
            {{ field.label_tag }}
            {{ field }}
        {% endfor %}
        <br>
        <br/>
        <button class="btn btn-primary" type="submit" name="submit">Add Category</button>
    </form>
</div>
{% endblock %}

www/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="{% static 'img/favicon.ico' %}">
        <title>
            Rango - {% block title_block %} How to Tango with Django! {% endblock %}
        </title>
    </head>
    <div>

    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'rango:index' %}">Rango</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'rango:index' %}">Home</a></li>
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a></li>
            {% if user.is_authenticated %}
                <li>
                    <a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/"><strong>({{ user.username }}) - Logout </a>
                </li>
            {% else %}
            <li>
                <a class="nav-link" href="{% url 'registration_register' %}">Sign Up</a>
            </li>
            <li>
                <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->

    <div class="container">
        <div class="row row-offcanvas row-offcanvas-right">
            <div class="col-xs-12 col-sm-9">
                <p class="pull-right visible-xs">
                    <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
                </p>
                <div class="row">
                    {% block body_block %}
                    {% endblock %}
                </div>
            </div>
            <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
                <div class="list-group">
                    <h3>All Categories</h3>
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
             </div>
            </div>
        </div>
    </div>
    <hr>

    <div class="container-fluid">
            <div class="col-sm-3 col-md-2">
                <footer>
                    <p>© Company 2017</p>
                </footer> <!-- /container -->
            </div>
            <div class="col-sm-9 col-md-10">

            </div>
        </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/offcanvas.css' %}">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <!-- custom js -->
    <script src="{% static 'js/navbar_active.js' %}"></script>

    </body>
</html>

www/templates/rango/base.old.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Rango -
        {% block title_block %}
            How to Tango with Django !
        {% endblock %}
    </title>
</head>
<body>
    <div>
        {% block sidebar_block %}
            {% get_category_list category %}
            {% if user.is_authenticated %}
                Logged in as - {{ user.username }}
            {% endif %}
        {% endblock %}
    </div>
    <div>
        {% block body_block %}
            This is the body_block's default content, if no inheriting template, didn't use this block
        {% endblock %}
    </div>
    <hr/>
    <div>
        <ul>
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Main Page</a></li>
            <li><a href="{% url 'rango:add_category' %}">Add new Category</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'auth_password_change' %}">Update Password</a></li>
                <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
            {% else %}
                <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</body>
</html>

www/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}

            <h2>
                {{ category.name }}
            </h2>

            <span><b>{{ category.likes }}</b> people liked this Category</span>
            {% if pages %}
                <ul>
                    {% for page in pages %}
                        <li><a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                            ({% if page.views > 1 %}
                                {{ page.views }} views
                            {% else %}
                                {{ page.views }} view
                            {% endif %})
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <strong>No pages currently in category</strong>
            {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add new Page</a>
        {% endif %}
    {% else %}
        <strong>The specified category does not exist! </strong>
    {% endif %}
    <hr/>
    <form class="form-inline" id="user_form" method="post" action="{% url 'rango:show_category' category.slug %}">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" size="50" name="query" value="{{ query }}" id="query"/>
        </div>
        <button class="btn btn-primary" type="submit" name="submit" value="search">Search</button>
    </form>
    <br/>
    <div>
        {% if result_list %}
            <h2>Search Results</h2>
            <div class="list-group">
                {% for result in result_list %}
                    <div class="list-group-item">
                        <h4 class="list-group-item-heading">
                            <a href="{{ result.link }}">{{ result.title }}</a>
                        </h4>
                        <p class="list-group-item-text">{{ result.summary }}</p>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}

www/templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == current_cat %}
                <li class="list-group-item">
                    <strong>
                        <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                    </strong>
                </li>
            {% else %}
                <li class="list-group-item">
                    <a class="active" href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

www/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Main Page
{% endblock %}

{% block body_block %}
<div>
    <!--<div>
        <img src="{% static 'img/rango.jpeg' %}" height="100px"
         alt="Picture of Rango" />
    </div>-->
    <div class="jumbotron">
        <h1 class="display-3">Rango says... </h1>
        {% if user.is_authenticated %}
            <h1>Hello there {{ user.username }}</h1>
        {% else %}
            <h1>Hey there partner ! <br/></h1>
        {% endif %}
    </div>
</div>
<div class="row marketing">
    <div class="col-lg-6">
        <h2>Most Liked Categories</h2>
        <p>
        {% if categories %}
            <ul class="list-group">
                {% for category in categories %}
                    <li class="list-group-item"><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a> </li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
        </p>
    </div>
    <div class="col-lg-6">
        <h2>Most Viewed Pages</h2>
        <p>
        {% if pages %}
            <ul class="list-group">
                {% for page in pages %}
                    <li class="list-group-item"><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else%}
            <strong>There are no pages present.</strong>
        {% endif %}
        </p>
    </div>
</div>
{% endblock %}

www/templates/rango/list_profiles.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    List Profiles
{% endblock %}

{% block body_block %}
    <h1>User Profiles</h1>
    <ul class="list-group">
        {% if userprofile_list%}
            {% for userprofile in userprofile_list %}
                <li class="list-group-item">
                    <img src="{{ MEDIA_URL }}{{ userprofile.picture }}" width="150" height="150" alt="{{ selecteduser.username }}"/>
                    <br/>
                    UserName: <a href="{% url 'rango:profile' userprofile.user.username %}">{{ userprofile.user.username }}</a>
                    <br/>
                    Website: {{ userprofile.website }} </li>
            {% endfor %}
        {% else %}
            <p>There are no users for the site.</p>
        {% endif %}
    </ul>
{% endblock %}

www/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login</h1>
    <hr/>

    <form id="login_form" method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}

        Username: <input type="text" name="username" value="" size="30"/>
        <br/> <br/>
        Password: <input type="password" name="password" value="" size="30"/>
        <br/>

        <input type="submit" value="Login"/>
    </form>
{% endblock %}

www/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Registration
{% endblock %}

{% block body_block %}
    <h1>Registration</h1>
    <hr/>

    {% if registered %}
        Rango Says: <strong>Thank you for the registration</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a><br/>
    {% else %}
        Rango Says: <strong>Register here!</strong><br/>
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Register"/>
        </form>
    {% endif %}
{% endblock %}

www/templates/rango/register.old.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Registration
{% endblock %}

{% block body_block %}
    <h1>Registration</h1>
    <hr/>

    {% if registered %}
        Rango Says: <strong>Thank you for the registration</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a><br/>
    {% else %}
        Rango Says: <strong>Register here!</strong><br/>
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Register"/>
        </form>
    {% endif %}
{% endblock %}